config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :stores, only: [:index, :show, :new, :create, :edit, :update]
  resources :items, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :store_items
    has_many :stores, through: :store_items
end

app/models/store.rb
class Store < ApplicationRecord
    has_many :store_items
    has_many :items, through: :store_items
end

app/models/store_item.rb
class StoreItem < ApplicationRecord
    belongs_to :item
    belongs_to :store
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def index
        @items = Item.all
    end

    def show
        @item = find_item
    end

    def new
        @item = Item.new
    end

    def create
        @item = Item.create(item_params(:name, :price, :sport, :store_ids => []))
        redirect_to item_path(@item)
    end

    def edit       
        find_item
    end     

    def update        
        find_item         
        @item.update(item_params(:name, :price, :sport, :store_ids => []))        
        redirect_to item_path(@item)    
    end

    private

    def item_params(*args)
        params.require(:item).permit(*args)
    end

    def find_item
        @item = Item.find(params[:id])
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

    def index
        @stores = Store.all
    end

    def show
        @store = find_store
    end

    def new
        @store = Store.new
    end

    def create
        @store = Store.create(store_params(:name, :city, :item_ids => []))
        redirect_to store_path(@store)
    end

    def edit       
        find_store
    end     

    def update      
        find_store         
        @store.update(store_params(:name, :city, :item_ids => []))        
        redirect_to store_path(@store)    
    end

    private

    def store_params(*args)
        params.require(:store).permit(*args)
    end

    def find_store
        @store = Store.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/items/edit.html.erb
<h1>Edit a Item</h1>

<div>
    <%= form_for @item do |f| %>
        <%= f.label "Item Name:" %>
        <%= f.text_field :name %><br />
        <%= f.label "Item Price:" %>
        <%= f.text_field :price %><br />
        <%= f.label "Item sport:" %>
        <%= f.select :sport, ["Football", "Basketball"]%> <br />
        <%= f.label "Select store:" %>
        <%= f.collection_check_boxes(:store_ids, Store.all, :id, :name) %><br />
        <br>
        <%= f.submit %>
    <% end %>
</div>

app/views/items/index.html.erb
<h1>Items</h1>

<ul>
    <% @items.each do |item| %>
        <li><%= link_to item.name, item_path(item.id) %></li>
    <% end %>
</ul>
<br>
<div>
    <%= link_to "Add New Item", new_item_path %>
</div>

app/views/items/new.html.erb
<h1>Creating a New Item</h1>

<div>
    <%= form_for @item do |f| %>
        <%= f.label "Item Name:" %>
        <%= f.text_field :name %><br />
        <%= f.label "Item Price:" %>
        <%= f.text_field :price %><br />
        <%= f.label "Item sport:" %>
        <%= f.text_field :sport %> <br />
        <%= f.submit %>
    <% end %>
</div>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<h2>Details</h2>
<ul>
    <li>Name: <%= @item.name %></li>
    <li>Price: <%= @item.price %></li>
    <li>Sport: <%= @item.sport %></li>
    <li>Stores:
        <ul>
            <% @item.stores.each do |store| %>
                <li><%= link_to store.name, store_path(store.id) %></li>
            <% end %>
        </ul>
    </li>
</ul>
<br>
<div>
<%= link_to "Go back to all items", items_path %>
<%= link_to "Edit this item",  edit_item_path %>
<%= link_to "Add Jersey to a store",  new_store_path%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SportingStoreCrudApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stores/edit.html.erb
<h1>Edit a Store</h1>

<div>
    <%= form_for @store do |f| %>
        <%= f.label "Store Name:" %>
        <%= f.text_field :name %><br />
        <%= f.label "Store City:" %>
        <%= f.text_field :city %> <br />
        <%= f.label "Select item to add:" %>
        <%= f.collection_check_boxes(:item_ids, Item.all, :id, :name) %><br />
        <br>
        <%= f.submit %>
    <% end %>
</div>

app/views/stores/index.html.erb
<h1>Stores</h1>

<ul>
    <% @stores.each do |store| %>
        <li><%= link_to store.name, store_path(store.id) %></li>
    <% end %>
</ul>
<br>
<div>
    <%= link_to "Add new store", new_store_path %>
</div>

app/views/stores/new.html.erb
<h1>Creating a New Store</h1>

<div>
    <%= form_for @store do |f| %>
        <%= f.label "Store Name:" %>
        <%= f.text_field :name %><br />
        <%= f.label "Store City:" %>
        <%= f.text_field :city %> <br />
        <%= f.label "Jerseys:" %>
        <%= f.collection_check_boxes(:item_ids, Item.all, :id, :name) %><br />
        <%= f.submit %>
    <% end %>

app/views/stores/show.html.erb
<h1><%= @store.name %></h1>

<h2>Details</h2>
<ul>
    <li>Name: <%= @store.name %></li>
    <li>City: <%= @store.city %></li>
    <li>Items:
        <ul>
            <% @store.items.each do |item| %>
                <li><%= link_to item.name, item_path(item.id) %></li>
            <% end %>
        </ul>
    </li>
</ul>
<br>
<div>
<%= link_to "Go back to all stores", stores_path %>
<%= link_to "Edit this store",  edit_store_path %>
</div>